### ISSUE TITLE
Using "listen none" to turn off all channels throws a string exception.

### ISSUE THREAD

**Issue by Arthmoor** [Arthmoor/AFKMud#8]
When trying to turn off all mutable channels via "listen none" the MUD dumps the following log:

Bugs: [*****] BUG: Command exception: 'basic_string::erase' on command: listen none
Bugs: Obtained 7 stack frames.
Bugs: interpret(char_data*, std::string)
Bugs: process_input()
Bugs: game_loop()
Bugs: ../src/afkmud(main+0x202)
Bugs: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)
Bugs: ../src/afkmud()
Log: [*****] LAG: Samson: listen none (R:1203 S:1416690772.610337)

All channels remain flagged as on once this happens.

The code in channels.cpp calls the following:
````c++
   if( !str_cmp( argument, "none" ) )
   {
      for( chan = chanlist.begin(  ); chan != chanlist.end(  ); ++chan )
      {
         channel = *chan;

         if( channel->flags.test( CHAN_ALWAYSON ) )
            continue;

         if( hasname( ch->pcdata->chan_listen, channel->name ) )
            removename( ch->pcdata->chan_listen, channel->name );
      }
      ch->print( "&YYou no longer listen to any available muteable channels.\r\n" );
      return;
   }
````

Which in turn calls this in editor.cpp:
````c++
/* Remove a member from a list, provided it's there. */
void removename( string & list, const string & member )
{
   if( !hasname( list, member ) )
      return;

   // Implies the list has more than just this name.
   if( list.length(  ) > member.length(  ) )
   {
      string die = " " + member;
      string::size_type pos = list.find( die );

      list.erase( pos, die.length(  ) );
   }
   else
      list.clear(  );
   strip_lspace( list );
}
````

It's the erase call being made in removename() that's actually breaking.

**Comment by burgerbutts** [comment]
I've put up a pull request with a fix for this, however there's a new bug relating to deleting channels with similar names.

**Comment by Arthmoor** [comment]
This issue has now been fixed. Thank you :)
